import type { Email, SecurityEvent } from './types';

export const emails: Email[] = [
  {
    id: '1',
    from: { name: 'Alice', email: 'alice@example.com' },
    to: [{ name: 'You', email: 'user@qymail.com' }],
    subject: 'Project Update',
    body: `Hi team,<br><br>Just a quick update on the Q3 project. We're on track to meet our deadlines. I've attached the latest progress report for your review. Please provide feedback by EOD Friday.<br><br>Best,<br>Alice`,
    date: '2024-05-20T10:00:00Z',
    read: true,
    attachments: [{ filename: 'progress_report_q3.pdf', size: '1.2MB' }],
    mailbox: 'inbox',
  },
  {
    id: '2',
    from: { name: 'Bob', email: 'bob@example.com' },
    to: [{ name: 'You', email: 'user@qymail.com' }],
    subject: 'Lunch tomorrow?',
    body: `Hey,<br><br>Are you free for lunch tomorrow? Thinking of trying that new Italian place downtown around 1 PM. Let me know!<br><br>Cheers,<br>Bob`,
    date: '2024-05-20T09:30:00Z',
    read: false,
    attachments: [],
    mailbox: 'inbox',
  },
  {
    id: '3',
    from: { name: 'Marketing Team', email: 'marketing@example.com' },
    to: [{ name: 'You', email: 'user@qymail.com' }],
    subject: 'Weekly Newsletter',
    body: `<h1>Our biggest sale of the year!</h1><p>Don't miss out on savings up to 50% on all our products. Click here to shop now!</p>`,
    date: '2024-05-19T15:00:00Z',
    read: true,
    attachments: [],
    mailbox: 'inbox',
  },
  {
    id: '4',
    from: { name: 'You', email: 'user@qymail.com' },
    to: [{ name: 'Charlie', email: 'charlie@example.com' }],
    subject: 'Re: Meeting Notes',
    body: `Hi Charlie,<br><br>Thanks for sending those over. I've added my comments to the document.<br><br>Thanks,`,
    date: '2024-05-18T14:00:00Z',
    read: true,
    attachments: [],
    mailbox: 'sent',
  },
  {
    id: '5',
    from: { name: 'Security Alert', email: 'security@yourbank.com' },
    to: [{ name: 'You', email: 'user@qymail.com' }],
    subject: 'Suspicious Login Attempt',
    body: `Dear customer,<br><br>We detected a suspicious login to your account from an unrecognized device. Please click here to verify your identity immediately: http://yourbank.secure-login-not-real.com/verify. If you do not verify within 24 hours, your account will be suspended.<br><br>Sincerely,<br>Your Bank Security Team`,
    date: '2024-05-17T11:45:00Z',
    read: false,
    attachments: [],
    mailbox: 'inbox',
  },
  {
    id: '6',
    from: { name: 'Old Colleague', email: 'dave@oldcompany.com' },
    to: [{ name: 'You', email: 'user@qymail.com' }],
    subject: 'Catching up',
    body: `Long time no see!<br><br>How have you been? It's been ages. We should grab a coffee sometime and catch up. Are you still in the city?<br><br>Best,<br>Dave`,
    date: '2024-05-16T18:00:00Z',
    read: true,
    attachments: [],
    mailbox: 'inbox',
  },
  {
    id: '7',
    from: { name: ' Nigerian Prince', email: 'urgent.business@royal-email.ng' },
    to: [{ name: 'You', email: 'user@qymail.com' }],
    subject: 'Urgent Business Proposal',
    body: `Dear Friend,<br><br>I am a Nigerian prince and I need your assistance in transferring the sum of $25,000,000 USD out of the country. For your help, you will receive 20% of the total sum. Please provide your full name, address, and bank account details so we can proceed.<br><br>This is very urgent and confidential.<br><br>Yours Faithfully,<br>Prince Ade`,
    date: '2024-05-15T08:20:00Z',
    read: true,
    attachments: [],
    mailbox: 'trash',
  },
    {
    id: '8',
    from: { name: 'You', email: 'user@qymail.com' },
    to: [{ name: 'Alice', email: 'alice@example.com' }],
    subject: 'Re: Project Update',
    body: `Hi Alice,<br><br>Thanks for the update. The report looks great, no major concerns from my side. Just one minor typo on page 5.<br><br>Best,`,
    date: '2024-05-20T14:20:00Z',
    read: true,
    attachments: [],
    mailbox: 'sent',
  },
];

export const securityEvents: SecurityEvent[] = [
  { id: 'evt1', userId: 'user@qymail.com', action: 'decrypt', outcome: 'success', timestamp: '2024-05-20T10:01:00Z', emailId: '1', emailSubject: 'Project Update' },
  { id: 'evt2', userId: 'user@qymail.com', action: 'decrypt', outcome: 'failure', reason: 'unauthorized', timestamp: '2024-05-20T11:05:00Z', emailId: 'unknown', emailSubject: 'Access to Charlie\'s mail' },
  { id: 'evt3', userId: 'user@qymail.com', action: 'send', outcome: 'success', timestamp: '2024-05-18T14:00:00Z', emailId: '4', emailSubject: 'Re: Meeting Notes' },
  { id: 'evt4', userId: 'attacker@evil.com', action: 'decrypt', outcome: 'failure', reason: 'unauthorized', timestamp: '2024-05-19T09:15:00Z', emailId: '2', emailSubject: 'Lunch tomorrow?' },
  { id: 'evt5', userId: 'attacker@evil.com', action: 'decrypt', outcome: 'failure', reason: 'unauthorized', timestamp: '2024-05-19T09:16:00Z', emailId: '2', emailSubject: 'Lunch tomorrow?' },
  { id: 'evt6', userId: 'user@qymail.com', action: 'decrypt', outcome: 'failure', reason: 'session_reused', timestamp: '2024-05-20T10:02:00Z', emailId: '1', emailSubject: 'Project Update' },
  { id: 'evt7', userId: 'user@qymail.com', action: 'decrypt', outcome: 'success', timestamp: '2024-05-20T09:31:00Z', emailId: '2', emailSubject: 'Lunch tomorrow?' },
  { id: 'evt8', userId: 'attacker@evil.com', action: 'decrypt', outcome: 'failure', reason: 'session_expired', timestamp: '2024-05-21T10:00:00Z', emailId: '1', emailSubject: 'Project Update' },
];
